# Generated by Django 4.0.4 on 2022-05-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ciudad', models.CharField(max_length=100)),
                ('nom_municipio', models.CharField(max_length=100)),
                ('nom_departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=80)),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono_empresa', models.CharField(max_length=10)),
                ('nombre_contact', models.CharField(max_length=80)),
                ('tel_contact', models.CharField(max_length=80)),
                ('email_contact', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comerciallist', to='inventarioslist_app.comercial')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ot',
            fields=[
                ('Ot', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarioslist_app.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='productos',
            field=models.ManyToManyField(related_name='productoslist', to='inventarioslist_app.producto'),
        ),
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='inventarioslist_app.empresa')),
                ('producto', models.ManyToManyField(related_name='productos', to='inventarioslist_app.producto')),
            ],
        ),
    ]
